### ISSUE TITLE
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

### ISSUE THREAD

**Issue by SungmanHong** [makinacorpus/easydict#25]
pip install git+https://github.com/makinacorpus/easydict

```
Collecting git+https://github.com/makinacorpus/easydict
  Cloning https://github.com/makinacorpus/easydict to c:\users\owner\appdata\local\temp\pip-req-build-f7qokfq9
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\owner\appdata\local\programs\python\python36\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\owner\\AppData\\Local\\Temp\\pip-req-build-f7qokfq9\\setup.py'"'"'; __file__='"'"'C:\\Users\\owner\\AppData\\Local\\Temp\\pip-req-build-f7qokfq9\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\owner\AppData\Local\Temp\pip-pip-egg-info-2s77kngi'
         cwd: C:\Users\owner\AppData\Local\Temp\pip-req-build-f7qokfq9\
    Complete output (28 lines):
    Traceback (most recent call last):
      File "c:\users\owner\appdata\local\programs\python\python36\lib\site-packages\pkg_resources\__init__.py", line 2480, in resolve
        return functools.reduce(getattr, self.attrs, module)
    AttributeError: type object 'Distribution' has no attribute '_finalize_feature_opts'

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\owner\AppData\Local\Temp\pip-req-build-f7qokfq9\setup.py", line 30, in <module>
        'Programming Language :: Python :: 3.6'],
      File "c:\users\owner\appdata\local\programs\python\python36\lib\site-packages\setuptools\__init__.py", line 163, in setup
        return distutils.core.setup(**attrs)
      File "c:\users\owner\appdata\local\programs\python\python36\lib\distutils\core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "c:\users\owner\appdata\local\programs\python\python36\lib\site-packages\setuptools\dist.py", line 430, in __init__
        k: v for k, v in attrs.items()
      File "c:\users\owner\appdata\local\programs\python\python36\lib\distutils\dist.py", line 281, in __init__
        self.finalize_options()
      File "c:\users\owner\appdata\local\programs\python\python36\lib\site-packages\setuptools\dist.py", line 720, in finalize_options
        for ep in sorted(eps, key=by_order):
      File "c:\users\owner\appdata\local\programs\python\python36\lib\site-packages\setuptools\dist.py", line 719, in <lambda>
        eps = map(lambda e: e.load(), pkg_resources.iter_entry_points(group))
      File "c:\users\owner\appdata\local\programs\python\python36\lib\site-packages\pkg_resources\__init__.py", line 2472, in load
        return self.resolve()
      File "c:\users\owner\appdata\local\programs\python\python36\lib\site-packages\pkg_resources\__init__.py", line 2482, in resolve
        raise ImportError(str(exc)) from exc
    ImportError: type object 'Distribution' has no attribute '_finalize_feature_opts'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by forechoandlook** [comment]
Try it with `pip`
