### ISSUE TITLE
pop(k, d) fails when key (k) doesn't exist (raises AttributeError)

### ISSUE THREAD

**Issue by shmuelyo** [makinacorpus/easydict#46]
Recommend you replace line 153 with:
```
if hasattr(self, k):
    delattr(self, k)
```

**Comment by leplatrem** [comment]
What do you have in mind?

Current behaviour:
```
>>> from easydict import EasyDict as edict
>>> d = edict({"a": 1})
>>> d.pop("b")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mathieu/Code/Mozilla/kinto/.venv/lib/python3.12/site-packages/easydict/__init__.py", line 153, in pop
    delattr(self, k)
AttributeError: 'EasyDict' object has no attribute 'b'
>>>
```

Matches default dict behaviour:
```
>>> d = {"a": 1}
>>> d.pop("b")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
KeyError: 'b'
>>> 
```

**Comment by mikecee** [comment]
I think this issue is about `pop(k, d)`, rather than `pop(k)`.  The expected behavior is :

```python
>>> # behavior of built-in dict
>>> foo=dict({"a": 1})
>>> foo.pop("b", 100)
100

>>> # desired behavior of easydict
>>> d = edict({"a": 1})
>>> d.pop("b", 100)
100
```

but what's happening is:

```python
>>> d = edict({"a": 1})
>>> d.pop("b", 100)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../lib/python3.11/site-packages/easydict/__init__.py", line 159, in pop
    delattr(self, k)
AttributeError: 'EasyDict' object has no attribute 'b'
```
