### ISSUE TITLE
python3.6_easydict

### ISSUE THREAD

**Issue by liu666666** [makinacorpus/easydict#8]
Thanks for your nice share! Could you please hele me solve the issue?
when i use conda with python2.7, i can install easydict successfully. however,
when i use conda with python3.6, i cannot install easydict successfully, the log shows that 

"UnsatisfiableError: The following specifications were found to be in conflict:
  - easydict -> python 2.7*
  - python 3.6*"

How can i install easydict with python3.6 . Thank you in advance!

**Comment by leplatrem** [comment]
I wonder if there's still anybody to maintain this project at Makina Corpus :)

You can take your chance by changing the classifiers here and submit a pull-request!
https://github.com/makinacorpus/easydict/blob/master/setup.py#L29

**Comment by Suor** [comment]
Any updates?

**Comment by leplatrem** [comment]
easydict is only a few lines, you can easily dig into it and submit a fix if you need it :)

**Comment by marongchao** [comment]
I sent out pull request just now for change, please check and merge code.

https://github.com/makinacorpus/easydict/pull/11

Thanks
Ma rongchao

**Comment by SungmanHong** [comment]
Hi I can't install it!! I'm python 3.6user


```
PS C:\Users\owner> pip install easydict
Collecting easydict
  Using cached easydict-1.9.tar.gz (6.4 kB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\owner\appdata\local\programs\python\python36\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\owner\\AppData\\Local\\Temp\\pip-install-gf9hvmq0\\easydict\\setup.py'"'"'; __file__='"'"'C:\\Users\\owner\\AppData\\Local\\Temp\\pip-install-gf9hvmq0\\easydict\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\owner\AppData\Local\Temp\pip-pip-egg-info-9yh7u5fa'
         cwd: C:\Users\owner\AppData\Local\Temp\pip-install-gf9hvmq0\easydict\
    Complete output (28 lines):
    Traceback (most recent call last):
      File "c:\users\owner\appdata\local\programs\python\python36\lib\site-packages\pkg_resources\__init__.py", line 2480, in resolve
        return functools.reduce(getattr, self.attrs, module)
    AttributeError: type object 'Distribution' has no attribute '_finalize_feature_opts'

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\owner\AppData\Local\Temp\pip-install-gf9hvmq0\easydict\setup.py", line 30, in <module>
        'Programming Language :: Python :: 3.6'],
      File "c:\users\owner\appdata\local\programs\python\python36\lib\site-packages\setuptools\__init__.py", line 163, in setup
        return distutils.core.setup(**attrs)
      File "c:\users\owner\appdata\local\programs\python\python36\lib\distutils\core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "c:\users\owner\appdata\local\programs\python\python36\lib\site-packages\setuptools\dist.py", line 430, in __init__
        k: v for k, v in attrs.items()
      File "c:\users\owner\appdata\local\programs\python\python36\lib\distutils\dist.py", line 281, in __init__
        self.finalize_options()
      File "c:\users\owner\appdata\local\programs\python\python36\lib\site-packages\setuptools\dist.py", line 720, in finalize_options
        for ep in sorted(eps, key=by_order):
      File "c:\users\owner\appdata\local\programs\python\python36\lib\site-packages\setuptools\dist.py", line 719, in <lambda>
        eps = map(lambda e: e.load(), pkg_resources.iter_entry_points(group))
      File "c:\users\owner\appdata\local\programs\python\python36\lib\site-packages\pkg_resources\__init__.py", line 2472, in load
        return self.resolve()
      File "c:\users\owner\appdata\local\programs\python\python36\lib\site-packages\pkg_resources\__init__.py", line 2482, in resolve
        raise ImportError(str(exc)) from exc
    ImportError: type object 'Distribution' has no attribute '_finalize_feature_opts'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
